### ISSUE TITLE
A wrapper plugin for PL-node

### ISSUE THREAD

**Issue by dave-cross** [EvanLovely/scss-to-json#1]
Evan!

Your module was so easy to use. I wrapped it in PL-node plugin so it runs every time a build happens.

Sharing it here so you're aware: https://github.com/cloudsociety/plugin-node-scsstojson

Any advice or changes/improvements gladly and humbly accepted.

Thank you for making scsstojson.

--Dave

**Comment by EvanLovely** [comment]
Great to hear; thanks so much! I've added your mention to my readme: e625d13
